browser: sh -c "cd ./client-in-browser && gopherjs version && gopherjs serve . --http 127.0.0.1:$PORT"
proxy: sh -c 'go build -i -o /tmp/badgerodon-simulator-demo-2-proxy ./proxy && /tmp/badgerodon-simulator-demo-2-proxy'
server: sh -c 'go build -i -o /tmp/badgerodon-simulator-demo-2-server ./server && /tmp/badgerodon-simulator-demo-2-server'