// Code generated by protoc-gen-go. DO NOT EDIT.
// source: routerpb.proto

/*
Package routerpb is a generated protocol buffer package.

It is generated from these files:
	routerpb.proto

It has these top-level messages:
	DialRequest
	DialResult
	ListenRequest
	ListenResult
	Data
	Message
*/
package routerpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DialRequest struct {
	Protocol string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *DialRequest) Reset()                    { *m = DialRequest{} }
func (m *DialRequest) String() string            { return proto.CompactTextString(m) }
func (*DialRequest) ProtoMessage()               {}
func (*DialRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DialRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *DialRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type DialResult struct {
	Handle int64 `protobuf:"varint,1,opt,name=handle" json:"handle,omitempty"`
}

func (m *DialResult) Reset()                    { *m = DialResult{} }
func (m *DialResult) String() string            { return proto.CompactTextString(m) }
func (*DialResult) ProtoMessage()               {}
func (*DialResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DialResult) GetHandle() int64 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type ListenRequest struct {
	Protocol string `protobuf:"bytes,1,opt,name=protocol" json:"protocol,omitempty"`
	Address  string `protobuf:"bytes,2,opt,name=address" json:"address,omitempty"`
}

func (m *ListenRequest) Reset()                    { *m = ListenRequest{} }
func (m *ListenRequest) String() string            { return proto.CompactTextString(m) }
func (*ListenRequest) ProtoMessage()               {}
func (*ListenRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListenRequest) GetProtocol() string {
	if m != nil {
		return m.Protocol
	}
	return ""
}

func (m *ListenRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type ListenResult struct {
	Handle int64 `protobuf:"varint,1,opt,name=handle" json:"handle,omitempty"`
}

func (m *ListenResult) Reset()                    { *m = ListenResult{} }
func (m *ListenResult) String() string            { return proto.CompactTextString(m) }
func (*ListenResult) ProtoMessage()               {}
func (*ListenResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListenResult) GetHandle() int64 {
	if m != nil {
		return m.Handle
	}
	return 0
}

type Data struct {
	Handle int64  `protobuf:"varint,1,opt,name=handle" json:"handle,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Data) Reset()                    { *m = Data{} }
func (m *Data) String() string            { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()               {}
func (*Data) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Data) GetHandle() int64 {
	if m != nil {
		return m.Handle
	}
	return 0
}

func (m *Data) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Message struct {
	// Types that are valid to be assigned to Message:
	//	*Message_DialRequest
	//	*Message_DialResult
	//	*Message_ListenRequest
	//	*Message_ListenResult
	//	*Message_Data
	Message isMessage_Message `protobuf_oneof:"message"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type isMessage_Message interface {
	isMessage_Message()
}

type Message_DialRequest struct {
	DialRequest *DialRequest `protobuf:"bytes,1,opt,name=dial_request,json=dialRequest,oneof"`
}
type Message_DialResult struct {
	DialResult *DialResult `protobuf:"bytes,2,opt,name=dial_result,json=dialResult,oneof"`
}
type Message_ListenRequest struct {
	ListenRequest *ListenRequest `protobuf:"bytes,3,opt,name=listen_request,json=listenRequest,oneof"`
}
type Message_ListenResult struct {
	ListenResult *ListenResult `protobuf:"bytes,4,opt,name=listen_result,json=listenResult,oneof"`
}
type Message_Data struct {
	Data *Data `protobuf:"bytes,5,opt,name=data,oneof"`
}

func (*Message_DialRequest) isMessage_Message()   {}
func (*Message_DialResult) isMessage_Message()    {}
func (*Message_ListenRequest) isMessage_Message() {}
func (*Message_ListenResult) isMessage_Message()  {}
func (*Message_Data) isMessage_Message()          {}

func (m *Message) GetMessage() isMessage_Message {
	if m != nil {
		return m.Message
	}
	return nil
}

func (m *Message) GetDialRequest() *DialRequest {
	if x, ok := m.GetMessage().(*Message_DialRequest); ok {
		return x.DialRequest
	}
	return nil
}

func (m *Message) GetDialResult() *DialResult {
	if x, ok := m.GetMessage().(*Message_DialResult); ok {
		return x.DialResult
	}
	return nil
}

func (m *Message) GetListenRequest() *ListenRequest {
	if x, ok := m.GetMessage().(*Message_ListenRequest); ok {
		return x.ListenRequest
	}
	return nil
}

func (m *Message) GetListenResult() *ListenResult {
	if x, ok := m.GetMessage().(*Message_ListenResult); ok {
		return x.ListenResult
	}
	return nil
}

func (m *Message) GetData() *Data {
	if x, ok := m.GetMessage().(*Message_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Message) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Message_OneofMarshaler, _Message_OneofUnmarshaler, _Message_OneofSizer, []interface{}{
		(*Message_DialRequest)(nil),
		(*Message_DialResult)(nil),
		(*Message_ListenRequest)(nil),
		(*Message_ListenResult)(nil),
		(*Message_Data)(nil),
	}
}

func _Message_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Message)
	// message
	switch x := m.Message.(type) {
	case *Message_DialRequest:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DialRequest); err != nil {
			return err
		}
	case *Message_DialResult:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.DialResult); err != nil {
			return err
		}
	case *Message_ListenRequest:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListenRequest); err != nil {
			return err
		}
	case *Message_ListenResult:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.ListenResult); err != nil {
			return err
		}
	case *Message_Data:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("Message.Message has unexpected type %T", x)
	}
	return nil
}

func _Message_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Message)
	switch tag {
	case 1: // message.dial_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DialRequest)
		err := b.DecodeMessage(msg)
		m.Message = &Message_DialRequest{msg}
		return true, err
	case 2: // message.dial_result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(DialResult)
		err := b.DecodeMessage(msg)
		m.Message = &Message_DialResult{msg}
		return true, err
	case 3: // message.listen_request
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListenRequest)
		err := b.DecodeMessage(msg)
		m.Message = &Message_ListenRequest{msg}
		return true, err
	case 4: // message.listen_result
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(ListenResult)
		err := b.DecodeMessage(msg)
		m.Message = &Message_ListenResult{msg}
		return true, err
	case 5: // message.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Data)
		err := b.DecodeMessage(msg)
		m.Message = &Message_Data{msg}
		return true, err
	default:
		return false, nil
	}
}

func _Message_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Message)
	// message
	switch x := m.Message.(type) {
	case *Message_DialRequest:
		s := proto.Size(x.DialRequest)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_DialResult:
		s := proto.Size(x.DialResult)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ListenRequest:
		s := proto.Size(x.ListenRequest)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_ListenResult:
		s := proto.Size(x.ListenResult)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *Message_Data:
		s := proto.Size(x.Data)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*DialRequest)(nil), "DialRequest")
	proto.RegisterType((*DialResult)(nil), "DialResult")
	proto.RegisterType((*ListenRequest)(nil), "ListenRequest")
	proto.RegisterType((*ListenResult)(nil), "ListenResult")
	proto.RegisterType((*Data)(nil), "Data")
	proto.RegisterType((*Message)(nil), "Message")
}

func init() { proto.RegisterFile("routerpb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0xdd, 0x36, 0x6d, 0xe8, 0xd9, 0xc9, 0xe0, 0x01, 0x45, 0xb0, 0xa0, 0x08, 0x21, 0x26,
	0x4b, 0x04, 0x24, 0x76, 0x28, 0x92, 0x07, 0x58, 0xfc, 0x07, 0x90, 0x8b, 0x2d, 0x88, 0x64, 0x9a,
	0x62, 0x3b, 0xbf, 0x80, 0x3f, 0x8e, 0x7a, 0x49, 0xd3, 0x74, 0x80, 0x85, 0x2d, 0x97, 0xcb, 0x7b,
	0xef, 0xde, 0x17, 0xc8, 0x7d, 0xd3, 0x46, 0xeb, 0xb7, 0x6b, 0xb1, 0xf5, 0x4d, 0x6c, 0xca, 0x47,
	0xa0, 0xab, 0x5a, 0x3b, 0x65, 0xbf, 0x5a, 0x1b, 0x22, 0x3f, 0x83, 0x13, 0x7c, 0xff, 0xd6, 0xb8,
	0x62, 0x72, 0x31, 0xb9, 0x5e, 0xaa, 0x61, 0xe6, 0x05, 0xa4, 0xda, 0x18, 0x6f, 0x43, 0x28, 0xa6,
	0xb8, 0xda, 0x8f, 0xe5, 0x25, 0x40, 0x67, 0x12, 0x5a, 0x17, 0xf9, 0x29, 0x2c, 0x3e, 0xf4, 0xc6,
	0x38, 0x8b, 0x0e, 0x33, 0xd5, 0x4f, 0xe5, 0x13, 0x64, 0xcf, 0x75, 0x88, 0x76, 0xf3, 0xbf, 0xb0,
	0x2b, 0x60, 0x7b, 0x9b, 0x3f, 0xe3, 0x2a, 0x48, 0x56, 0x3a, 0xea, 0xdf, 0xf6, 0x9c, 0x43, 0x62,
	0x74, 0xd4, 0x68, 0xcf, 0x14, 0x3e, 0x97, 0xdf, 0x53, 0x48, 0x5f, 0x6c, 0x08, 0xfa, 0xdd, 0xf2,
	0x1b, 0x60, 0xa6, 0xd6, 0xee, 0xd5, 0x77, 0xd7, 0xa2, 0x9a, 0x56, 0x4c, 0x8c, 0x70, 0x49, 0xa2,
	0xa8, 0x19, 0xd1, 0x13, 0x40, 0x7b, 0xc9, 0xee, 0x32, 0x74, 0xa6, 0x15, 0x15, 0x07, 0x36, 0x92,
	0x28, 0x30, 0x07, 0x52, 0xf7, 0x90, 0x3b, 0xac, 0x32, 0x84, 0xcc, 0x50, 0x92, 0x8b, 0x23, 0x50,
	0x92, 0xa8, 0xcc, 0x1d, 0x91, 0xbb, 0x83, 0x6c, 0x10, 0x62, 0x54, 0x82, 0xba, 0x4c, 0x8c, 0xc9,
	0x48, 0xa2, 0x98, 0x1b, 0x93, 0x3a, 0xef, 0x1b, 0xcf, 0xf1, 0xe3, 0xb9, 0xd8, 0xe1, 0x91, 0xa4,
	0xab, 0xfe, 0xb0, 0x84, 0xf4, 0xb3, 0x6b, 0xbe, 0x5e, 0xe0, 0x5f, 0xb8, 0xfd, 0x09, 0x00, 0x00,
	0xff, 0xff, 0xa5, 0x0d, 0x0d, 0x47, 0x2c, 0x02, 0x00, 0x00,
}
