// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meshpb.proto

/*
Package meshpb is a generated protocol buffer package.

It is generated from these files:
	meshpb.proto

It has these top-level messages:
	Message
*/
package meshpb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MessageType int32

const (
	MessageType_DIAL   MessageType = 0
	MessageType_LISTEN MessageType = 1
	MessageType_DATA   MessageType = 3
	MessageType_ACK    MessageType = 4
)

var MessageType_name = map[int32]string{
	0: "DIAL",
	1: "LISTEN",
	3: "DATA",
	4: "ACK",
}
var MessageType_value = map[string]int32{
	"DIAL":   0,
	"LISTEN": 1,
	"DATA":   3,
	"ACK":    4,
}

func (x MessageType) String() string {
	return proto.EnumName(MessageType_name, int32(x))
}
func (MessageType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Message struct {
	Type MessageType `protobuf:"varint,1,opt,name=type,enum=MessageType" json:"type,omitempty"`
	Data []byte      `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *Message) Reset()                    { *m = Message{} }
func (m *Message) String() string            { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()               {}
func (*Message) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Message) GetType() MessageType {
	if m != nil {
		return m.Type
	}
	return MessageType_DIAL
}

func (m *Message) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "Message")
	proto.RegisterEnum("MessageType", MessageType_name, MessageType_value)
}

func init() { proto.RegisterFile("meshpb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 141 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xc9, 0x4d, 0x2d, 0xce,
	0x28, 0x48, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0xb2, 0xe7, 0x62, 0xf7, 0x4d, 0x2d, 0x2e,
	0x4e, 0x4c, 0x4f, 0x15, 0x52, 0xe0, 0x62, 0x29, 0xa9, 0x2c, 0x48, 0x95, 0x60, 0x54, 0x60, 0xd4,
	0xe0, 0x33, 0xe2, 0xd1, 0x83, 0x8a, 0x87, 0x54, 0x16, 0xa4, 0x06, 0x81, 0x65, 0x84, 0x84, 0xb8,
	0x58, 0x52, 0x12, 0x4b, 0x12, 0x25, 0x98, 0x14, 0x18, 0x35, 0x78, 0x82, 0xc0, 0x6c, 0x2d, 0x33,
	0x2e, 0x6e, 0x24, 0x85, 0x42, 0x1c, 0x5c, 0x2c, 0x2e, 0x9e, 0x8e, 0x3e, 0x02, 0x0c, 0x42, 0x5c,
	0x5c, 0x6c, 0x3e, 0x9e, 0xc1, 0x21, 0xae, 0x7e, 0x02, 0x8c, 0x60, 0x51, 0xc7, 0x10, 0x47, 0x01,
	0x66, 0x21, 0x76, 0x2e, 0x66, 0x47, 0x67, 0x6f, 0x01, 0x96, 0x24, 0x36, 0xb0, 0xfd, 0xc6, 0x80,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x0b, 0x68, 0x57, 0xd9, 0x8f, 0x00, 0x00, 0x00,
}
